### ISSUE TITLE
[Bug Report]: Crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [TechDevOnGitHub/Lux-Shader#12]
### Describe the bug

When I enable the shader pack (Lux-EA-B3) it causes my game to crash. 

https://mclo.gs/Sxn5UMQ

### To reproduce

1. Start Minecraft 
2. Activate shader
3. Crash

### Hardware specification

Apple M1 Pro

### Software specification

-Fabric 1.19.2- Iris 1.4.0

Mods:

3dskinlayers-fabric-1.5.2-mc1.19.1.jar
accurate-maps-1.0-BETA+1.19.jar
advancedtooltips-1.6.0+1.19.jar
advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
alternate-current-mc1.19-1.4.0.jar
AmbientEnvironment-fabric-1.19.2-8.0+3.jar
AmbientSounds_FABRIC_v5.2.5_mc1.19.2.jar
amecs-1.3.8+mc.1.19-rc2.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.2.46-fabric.jar
ArrowCam-1.0.1(1).jar
audio_engine_tweaks-1.2.3-1.19 build 3.jar
auditory-0.0.3-1.19.x.jar
bedrockwaters-1.7.1+1.19.2.jar
bendy-lib-fabric-2.1.1.jar
better-dark-mode-2.1.0.jar
BetterAnimationsCollection-v4.0.2-1.19.2-Fabric.jar
betterbeds-1.2.0.jar
betterbiomeblend-1.19.0-1.3.6-fabric.jar
BetterF3-1.4.0-Fabric-1.19.2.jar
bettermounthud-1.2.0.jar
betterstats-1.4.3.jar
BetterThirdPerson-Fabric-1.19-1.8.1.jar
BiomeParticleWeather-v4.0.2-1.19-Fabric.jar
Blanket Client tweaks-1.1.2.jar
block-entity-extended-rendering-2.0.0.jar
blur-2.6.0.jar
Bookshelf-Fabric-1.19.2-16.1.5.jar
brokenleadwarner-1.0.0+1.19.2.jar
CameraOverhaul-1.3.1-fabric-universal.jar
Capes-1.4.5+1.19.jar
cardinal-components-api-5.0.2.jar
catalogue-fabric-1.6.3-1.19.2.jar
cave_dust-1.2.0.jar
cem-0.7.1.jar
chat_heads-0.7.1-fabric-1.19.1.jar
chat-coords-0.2.2233.jar
chatcalc-3.0.12.jar
chime-1.3.0.jar
CITResewn-1.1.2+1.19.2.jar
ClearDespawn-fabric-1.19.2-1.1.9.jar
cloth-config-8.2.88-fabric.jar
collective-fabric-1.19.2-5.4.jar
colormatic-3.1.2+mc.1.19.jar
colour-my-servers-1.0.2.jar
compacthelpcommand-fabric_1.19.2-1.7.jar
completeconfig-2.0.0.jar
condensed_creative-2.0.0+1.19-fabric.jar
configured-fabric-2.0.0-1.19.2.jar
continuity-2.0.1+1.19.jar
Controlling-fabric-1.19.2-10.0+6.jar
cr-compass-ribbon-fabric-2.8.2+1.19.1.jar
CraftPresence-1.19.2-Release-1.9.2-universal.jar
CreativeCore_FABRIC_v2.8.5_mc1.19.2.jar
ctm-fabric-1.0.0+1.19.jar
ctrlq-fabric-mc1.18+-1.8.jar
dark-graph-1.0.2.jar
DeathFinder-v4.1.1-1.19.2-Fabric.jar
Debugify-2.7.1.jar
DetailArmorBar-2.6.2+1.19-fabric.jar
disguiseheads-fabric-1.0.0-mc1.19.2.jar
DistinguishedPotions-v4.0.1-1.19.2-Fabric.jar
DripSounds-1.19-0.3.0.jar
dyed-fabric-22w14a-1.0.2.jar
dynamic-fps-2.2.0.jar
eating-animation-1.9.jar
elytra-recast-2.2.1.jar
ElytraPhysics-1.1.1.jar
emoji-type-2.0.1+1.19.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.5.jar
enhanced-searchability-mc1.19-3.0.1+build.9.jar
enhancedblockentities-0.7.1+1.19.jar
entity_texture_features_fabric_1.19.x-4.1.1.jar
entity-view-distance-1.0.2+1.19.jar
entityculling-fabric-1.5.2-mc1.19.jar
Essential-fabric_1-19.jar
exordium-fabric-1.0.1-mc1.19.2.jar
extrasounds-2.3.1+1.19.2-1.19.1.jar
Fabric-1.19-SmoothSwapping-0.4.5.jar
fabric-api-0.62.0+1.19.2.jar
fabric-language-kotlin-1.8.4+kotlin.1.7.20.jar
fabricskyboxes-1.19.2-0.5.8.jar
fabrishot-1.9.1.jar
fallingleaves-1.12.2+1.19.2.jar
ferritecore-5.0.0-fabric.jar
firstperson-fabric-2.2.0-mc1.19.2.jar
ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric.jar
FPS-Monitor-1.19-1.3.0-Fabric.jar
GoogleChat-0.4.2.jar
grabcraft-litematic-1.19.1-fabric0.58.5-0.5.jar
graphutil-fabric-1.0.0-mc1.19.jar
hatlist-1.3.jar
Highlighter-1.19.1-fabric-1.1.4.jar
HorseDebug-1.2.4.jar
Iceberg-1.19.1-fabric-1.0.46.jar
illuminations-1.10.8.jar
indium-1.0.9+mc1.19.2.jar
inventory-control-tweaks-1.3.18+MC1.19-1.19.2.jar
inventoryfullalert-1.1.0-1.19.jar
iris-mc1.19.2-1.4.0.jar
item-model-fix-1.0.3+1.19.jar
ItemPhysicLite_FABRIC_v1.5.2_mc1.19.1.jar
Jade-1.19.1-fabric-8.2.1.jar
jsonem-0.1.2+1.19.jar
lambdabettergrass-1.3.0+1.19.jar
lambdynamiclights-2.1.2+1.19.jar
lazy-language-loader-0.3.1.jar
lazydfu-0.1.3.jar
LetSleepingDogsLie-1.19.2-1.1.1.jar
libjf-3.1.0.jar
lighty-1.0.5+1.19.1.jar
litematica-fabric-1.19.2-0.12.4.jar
lithium-fabric-mc1.19.2-0.8.3.jar
lunade-fastanim-1.5.6-1.19.jar
make_bubbles_pop-0.0.2-1.19.jar
malilib-fabric-1.19.2-0.13.0.jar
mazeworld-1.19.2-1.1.0.jar
mbp-1.4.jar
mcmouser-1.19-fabric-1.0.0.jar
memoryleakfix-1.19.1-0.7.0.jar
menulogue-fabric-1.0.1-1.19.2.jar
MerchantMarkers-1.19.1-fabric-1.2.3.jar
microdurability-0.3.6+1.19.jar
midnightcontrols-1.6.0+1.19.jar
midnightlib-0.6.1.jar
minihud-fabric-1.19.2-0.23.3.jar
modelfix-1.4-universal.jar
modmenu-4.0.6.jar
morechathistory-1.19.1-1.1.1.jar
moreculling-1.19.1-0.10.0.jar
moremcmeta-1.19-3.0.5-fabric.jar
MouseTweaks-fabric-mc1.19-2.22.jar
movement-vision-1.3.0.jar
multiple-server-lists-mc1.19.1-3.0.2+build.10.jar
nether-coords-1.19.2-1.1.1.jar
niceload-0.1.3.jar
NoChatReports-FABRIC-1.19.2-v1.13.9.jar
notenoughanimations-fabric-1.6.1-mc1.19.1.jar
numeralping-1.0.4.jar
optigui-1.1.6.jar
ostOverhaul-0.2.6-1.19.jar
PetOwner-1.8.3-1.19+.jar
PickUpNotifier-v4.2.0-1.19.2-Fabric.jar
player-animation-lib-fabric-0.4.0-test1.jar
pling-1.5.0.jar
PresenceFootsteps-1.6.2.jar
puzzle-1.4.0-1.19.jar
PuzzlesLib-v4.3.9-1.19.2-Fabric.jar
raised-fabric-1.19-1.1.2.jar
reacharound+1.19-1.1.0.jar
recursive-resources-2.2.1+1.19.jar
reeses_sodium_options-1.4.7+mc1.19.2-build.59.jar
rer-2.6.0.jar
resourcefullib-fabric-1.19.1-1.1.1.jar
respackopts-4.0.2.jar
roughly-searchable-2.5.0+1.19.jar
RoughlyEnoughItems-9.1.550.jar
RoughlyEnoughProfessions-fabric-1.19-1.1.2.jar
RoughlyEnoughTrades-1.19-1.0.jar
satin-1.9.0.jar
sheepconsistency-1.0.4.jar
show-me-your-skin-1.3.4+1.19.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.11+mc1.19.2-build.68.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
soundphysics-fabric-1.19.2-1.0.15.jar
starlight-1.1.1+fabric.ae22326.jar
statssearch-1.19.1-fabric0.58.5-1.0.1.jar
status-effect-bars-1.0.1+1.19.jar
statuseffecttimer-1.1.1+1.19.jar
talkbubbles-1.0.2.jar
TerraBlender-fabric-1.19.2-2.0.1.128.jar
testworld-1.0.0.jar
third-person-maps-1.4.0+1.19.jar
thorium-1.3.2.jar
timestamp-chat-2.2.4.jar
tooltipsplus-1.3.0+1.19.jar
tooltiptweaks-1.1.0.jar
toomanybinds-0.3.2+1.19.jar
transparent-5.1.0+1.19-fabric.jar
visualoverhaul-4.1.1.jar
vmp-fabric-mc1.19.2-0.2.0+beta.7.5-all.jar
waveycapes-fabric-1.2.1-mc1.19.1.jar
waxednotwaxed-1.1.3.jar
weaponmaster-multi-fabric-1.19-3.0.2.jar
whats-that-slot-fabric-1.3.1+1.19.2.jar
wmitaf-fabric-mc1.19-3.1.0.jar
worldtime-1.19.1-fabric0.58.5-1.3.1.jar
YetAnotherConfigLib-1.5.0.jar

**Comment by TechDevOnGitHub** [comment]
Hey, thank you for reaching out!

Mods are considered as 3rd party client modification, so I won't be fixing issues related to mods if I don't know what mod specifically causes the issue.

You can try loading the shader pack on a vanilla client to see if the mods are the problem, that would be neat. If the mods *are* the problem, please try to narrow it down to the mod(s) that cause(s) the problem.

In the meanwhile I'll see if there is any obvious fix for this.

If the game crashes again please send the crash log so I can narrow the problem down.

Thanks!

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/hx737Hr

modmenu-4.0.6.jar
fabric-api-0.62.0+1.19.2.jar
iris-mc1.19.2-1.4.0.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.2-0.8.3.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar

Still crashes on startup with these mods.

**Comment by Aces-and-Jacks** [comment]
They're used by almost everyone so it'd be a bit weird if these caused a crash. Maybe it has to do with using polymc

**Comment by aljustiet01** [comment]
Same issue

**Comment by glennmause** [comment]
I have the same Issue.

I have Minecraft 1.20.1, Forge 47.1.0, OptiFine HD U I5 (latest version, downloaded and installed today), and the latest version of the Shader.
I am on an M1 Mac, Minecraft also tells me OpenGL: 4.1 Metal - 76.3, Apple, Apple M1.
I have no other Mods installed.

Crash Report: 
`---- Minecraft Crash Report ----
// You're mean.

Time: 2023-08-22 15:10:27
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledFuture.isDone()" because "this.windowTick" is null
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.setupMinecraftWindow(DisplayWindow.java:523) ~[fmlearlydisplay-1.20.1-47.1.0.jar%2399!/:1.0] {}
	at net.minecraftforge.fml.loading.ImmediateWindowHandler.setupMinecraftWindow(ImmediateWindowHandler.java:54) ~[fmlloader-1.20.1-47.1.0.jar%2398!/:1.0] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callLong(Reflector.java:805) ~[OptiFine_1.20.1_HD_U_I5.jar%23159!/:?] {re:classloading}
	at net.optifine.reflect.ReflectorMethod.callLong(ReflectorMethod.java:154) ~[OptiFine_1.20.1_HD_U_I5.jar%23159!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:111) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:440) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.setupMinecraftWindow(DisplayWindow.java:523) ~[fmlearlydisplay-1.20.1-47.1.0.jar%2399!/:1.0] {}
	at net.minecraftforge.fml.loading.ImmediateWindowHandler.setupMinecraftWindow(ImmediateWindowHandler.java:54) ~[fmlloader-1.20.1-47.1.0.jar%2398!/:1.0] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callLong(Reflector.java:805) ~[OptiFine_1.20.1_HD_U_I5.jar%23159!/:?] {re:classloading}
	at net.optifine.reflect.ReflectorMethod.callLong(ReflectorMethod.java:154) ~[OptiFine_1.20.1_HD_U_I5.jar%23159!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:111) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:440) ~[client-1.20.1-20230612.114412-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (aarch64) version 12.6
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 262308880 bytes (250 MiB) / 503316480 bytes (480 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 11699.98
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1028.19
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.1.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.20.1_HD_U_I5
	OptiFine Build: 20230707-211226
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 8`

**Comment by Moresteck** [comment]
https://paste.ee/p/RKlZB
Same issue. No other mods installed, just:
fabric-api-0.96.0+1.20.4
sodium-fabric-0.5.8+mc1.20.4
iris-mc1.20.4-1.6.17

(And btw, my Java is not 32-bit. It's aarch64)

**Comment by TechDevOnGitHub** [comment]
All of you seem to have a slightly different issues, all resulting in a crash. I will take a look at all the logs soon and potentially split the Issue into multiple for better management. In the meantime, try out the latest version of the pack unless you already did.

**Comment by Moresteck** [comment]
Hello again, is there any update on the issue? Tried the latest commit, still crashes.

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/c1YfBU7

fabric-api-0.99.4+1.20.6.jar
indium-1.0.30+mc1.20.4.jar
iris-1.7.0+mc1.20.6.jar
lithium-fabric-mc1.20.6-0.12.3.jar
sodium-fabric-0.5.8+mc1.20.6.jar

Since I was reminded of this issue here's an update on latest dev release

Fabric 0.15.11 version 1.20.6

**Comment by TechDevOnGitHub** [comment]
@Aces-and-Jacks your issue seems to be related to user authentication, not the mod.

> [14:03:48] [Download-2/ERROR]: Failed to fetch user properties
> 214 | com.mojang.authlib.exceptions.AuthenticationException ...

@Moresteck do your log errors say the same thing? Otherwise it might actually be related to your java distribution, which I don't think I can offer support for as I have no way to test it.

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/BwMGX7c

how about now?

**Comment by TechDevOnGitHub** [comment]
@Aces-and-Jacks I'm surprised that this bug is supposedly caused by the shaderpack.
It's a crash that happened completely outside of the Java Virtual Machine - the part I don't have access to.
It might be related to an antivirus or other similarly agressive software according to [this article](https://inside.java/2020/12/03/crash-outside-the-jvm/). I will ask my developer friends if something similar ever happened for them and if they've managed to fix it, but I'd be surprised if that was the case.

**Comment by Moresteck** [comment]
> @Moresteck do your log errors say the same thing? Otherwise it might actually be related to your java distribution, which I don't think I can offer support for as I have no way to test it.

https://mclo.gs/8zNQaSv
Yes, exact same crash. And this time around it's Java 21 by Azul. I very much doubt it's about Java.

**Comment by Aces-and-Jacks** [comment]
I would post the java error file, I just don't know if there's any identifiers in there
